workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      # Set up Flutter SDK
      - name: Set up Flutter
        script: flutter --version

      # Get dependencies
      - name: Get dependencies
        script: flutter pub get

      # Decode key.properties from Base64
      - name: Decode key.properties
        script: |
          echo "$CM_KEY_PROPERTIES" | base64 --decode > android/key.properties

      # Decode keystore from Base64
      - name: Decode keystore
        script: |
          echo "$CM_BASE64_KEYSTORE" | base64 --decode > android/app/codemagic.keystore

      # Set up signing configuration using the new variables
      - name: Set up signing configuration
        script: |
          echo "storeFile=$CM_KEYSTORE_PATH" >> android/key.properties
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties

      # Build AAB in release mode (ensure release flag is set)
      - name: Build AAB
        script: flutter build appbundle --release



    artifacts:
      - "build/app/outputs/bundle/release/app-release.aab"
